[package]
name = "gfx_kiss"
version = "0.1.0"
authors = ["Dzmitry Malyshau <kvarkus@gmail.com>"]

[dependencies]
cgmath = "0.12"
env_logger = "0.3"
genmesh = "0.4"
gfx = "0.12"
gfx_device_gl = "0.11"
gfx_window_glutin = "0.12"
glutin = "0.6"
image = "0.10"
